FROM node:20

# Instalar ffmpeg para el backend
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Comando principal para arrancar el backend en modo desarrollo usando turbo
CMD ["sh", "-c", "npm install && npm run dev:backend"]
