// Tipos para el panel de administración

export interface AdminUser {
  /** Correo de Google del administrador */
  email: string;
  /** Nombre visible de la cuenta Google */
  name: string;
  /** URL del avatar de Google */
  picture: string;
  /** ID/shortcode de la estación en AzuraCast */
  stationId: string;
  stationName?: string;
  /** JWT de sesión emitido por nuestro backend */
  token: string;
}

export interface AdminStationStatus {
  id: number;
  name: string;
  shortcode: string;
  is_public: boolean;
  storage_quota: string;
  storage_used: string;
  is_online: boolean;
  listeners_unique: number;
  listeners_total: number;
}

export interface AdminPlaylist {
  id: number;
  name: string;
  type: string;
  source: string;
  order: string;
  remote_url: string | null;
  status: string;
  is_enabled: boolean;
  is_jingle: boolean;
  play_per_songs: number;
  play_per_minutes: number;
  play_per_hour_minute: number;
  weight: number;
  include_in_requests: boolean;
  include_in_on_demand: boolean;
  num_songs: number;
  total_length: number;
  links: { self: string };
}

export interface MediaFile {
  unique_id: string;
  song_id: string;
  path: string;
  title: string;
  artist: string;
  album: string;
  genre: string;
  length: number;
  length_text: string;
  custom_fields: Record<string, string>;
  playlists: { id: number; name: string }[];
  links: { self: string; art: string; download: string };
}

export interface AdminSongRequest {
  id: string;
  song: {
    id: string;
    text: string;
    artist: string;
    title: string;
    album: string;
    art: string;
  };
  timestamp: number;
  skip_delay: boolean;
  played_at: number | null;
}

export interface Streamer {
  id: number;
  streamer_username: string;
  streamer_password: string;
  display_name: string;
  comments: string;
  is_active: boolean;
  enforce_schedule: boolean;
  reactivate_at: number | null;
  art_updated_at: number;
  links: { self: string; art: string };
}

export interface ScheduleCategory {
  id: string;
  name: string;
  description: string | null;
  color: string;
  icon: string;
  keywords: string;
  isVisible: boolean;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

/** Public summary of a schedule category sent to listeners */
export interface ScheduleCategorySummary {
  id: string;
  name: string;
  description: string | null;
  color: string;
  icon: string;
}

export interface ScheduleItem {
  id: number;
  start_timestamp: number;
  start: string;
  end_timestamp: number;
  end: string;
  is_now: boolean;
  type: 'playlist' | 'streamer';
  title: string;
  category?: ScheduleCategorySummary | null;
  /** Number of consecutive AzuraCast slots merged into this entry */
  slots?: number;
}

export interface ListenerStats {
  total: number;
  unique: number;
  current: number;
}

export interface ListenerDetail {
  ip: string;
  user_agent: string;
  connected_on: number;
  connected_time: number;
  mount_name: string;
  location: {
    city: string;
    country: string;
    lat: number | null;
    lon: number | null;
  };
}

/** Announcement template used by the TTS locutor */
export interface LocutorTemplate {
  id: string;
  type: string;
  name: string;
  textTemplate: string;
  voice: string;
  speed: number;
  active: boolean;
  createdAt: string;
  updatedAt: string;
}

/** Payload to create or update a locutor template (camelCase in, snake_case on the wire) */
export interface LocutorTemplateInput {
  type: string;
  name: string;
  textTemplate: string;
  voice: string;
  speed: number;
  active: boolean;
}

/** Audio generated by the TTS locutor */
export interface LocutorAudio {
  id: string;
  filename: string;
  filepath: string;
  textRendered: string;
  durationMs: number | null;
  fileSizeBytes: number | null;
  voice: string;
  azuracastMediaId: string | null;
  generatedAt: string;
  status: string;
  hourValue: number | null;
  timeSlotGroup: string | null;
  useCount: number;
  template: { name: string; type: string } | null;
}

/** Entry of the TTS generation log */
export interface LocutorGenerationLog {
  id: string;
  jobType: string;
  status: string;
  details: string | null;
  audiosGenerated: number | null;
  durationMs: number | null;
  startedAt: string;
  finishedAt: string | null;
}

/** Health summary of the TTS locutor */
export interface LocutorStatus {
  kokoro: { healthy: boolean };
  last_job: LocutorGenerationLog | null;
  bank: { ready: number; pending: number; error: number };
  stats: Record<string, unknown>;
  timestamp: string;
}

/** Device registered by the mobile app for FCM notifications */
export interface AdminDevice {
  deviceId: string;
  hasFcmToken: boolean;
  platform: string | null;
  appVersion: string | null;
  subscriptions: string[];
  lastSeen: string;
  createdAt: string;
}

export interface AdminDeviceList {
  rows: AdminDevice[];
  total: number;
  page: number;
  totalPages: number;
}

/** Summary of program push notifications sent (admin dashboard cards) */
export interface NotificationStats {
  totalAll: number;
  total7d: number;
  byProgram: { programId: string; count: number }[];
}

/** Connected worker node reported by the worker pool */
export interface WorkerNodeInfo {
  workerId: string;
  name: string;
  status: string;
  maxConcurrentJobs: number;
  currentJobs: number;
  currentJobId: string | null;
  lastSeenAt: string | null;
}

/** YouTube processing job with its video summary */
export interface WorkerJob {
  id: string;
  videoId: string;
  status: string;
  attempts: number;
  lastError: string | null;
  startedAt: string | null;
  finishedAt: string | null;
  deadlineAt: string | null;
  nextRetryAt: string | null;
  createdAt: string;
  video: { title: string; videoId: string };
}
