// Tipos para el panel de administración

export interface AdminUser {
  /** Correo de Google del administrador */
  email: string;
  /** Nombre visible de la cuenta Google */
  name: string;
  /** URL del avatar de Google */
  picture: string;
  /** ID/shortcode de la estación en AzuraCast */
  stationId: string;
  stationName?: string;
  /** JWT de sesión emitido por nuestro backend */
  token: string;
}

export interface AdminStationStatus {
  id: number;
  name: string;
  shortcode: string;
  is_public: boolean;
  storage_quota: string;
  storage_used: string;
  is_online: boolean;
  listeners_unique: number;
  listeners_total: number;
}

export interface AdminPlaylist {
  id: number;
  name: string;
  type: string;
  source: string;
  order: string;
  remote_url: string | null;
  status: string;
  is_enabled: boolean;
  is_jingle: boolean;
  play_per_songs: number;
  play_per_minutes: number;
  play_per_hour_minute: number;
  weight: number;
  include_in_requests: boolean;
  include_in_on_demand: boolean;
  num_songs: number;
  total_length: number;
  links: { self: string };
}

export interface MediaFile {
  unique_id: string;
  song_id: string;
  path: string;
  title: string;
  artist: string;
  album: string;
  genre: string;
  length: number;
  length_text: string;
  custom_fields: Record<string, string>;
  playlists: { id: number; name: string }[];
  links: { self: string; art: string; download: string };
}

export interface AdminSongRequest {
  id: string;
  song: {
    id: string;
    text: string;
    artist: string;
    title: string;
    album: string;
    art: string;
  };
  timestamp: number;
  skip_delay: boolean;
  played_at: number | null;
}

export interface Streamer {
  id: number;
  streamer_username: string;
  streamer_password: string;
  display_name: string;
  comments: string;
  is_active: boolean;
  enforce_schedule: boolean;
  reactivate_at: number | null;
  art_updated_at: number;
  links: { self: string; art: string };
}

export interface ScheduleCategory {
  id: string;
  name: string;
  description: string | null;
  color: string;
  icon: string;
  keywords: string;
  isVisible: boolean;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

/** Public summary of a schedule category sent to listeners */
export interface ScheduleCategorySummary {
  id: string;
  name: string;
  description: string | null;
  color: string;
  icon: string;
}

export interface ScheduleItem {
  id: number;
  start_timestamp: number;
  start: string;
  end_timestamp: number;
  end: string;
  is_now: boolean;
  type: 'playlist' | 'streamer';
  title: string;
  category?: ScheduleCategorySummary | null;
  /** Number of consecutive AzuraCast slots merged into this entry */
  slots?: number;
}

export interface ListenerStats {
  total: number;
  unique: number;
  current: number;
}

/** Punto del historial de oyentes para la gráfica del dashboard */
export interface ListenerHistoryPoint {
  recordedAt: string;
  current: number;
  unique: number;
  total: number;
}

export interface ListenerHistoryResponse {
  rows: ListenerHistoryPoint[];
}

export interface ListenerDetail {
  ip: string;
  user_agent: string;
  connected_on: number;
  connected_time: number;
  mount_name: string;
  location: {
    city: string;
    country: string;
    lat: number | null;
    lon: number | null;
  };
}

/** Announcement template used by the TTS locutor */
export interface LocutorTemplate {
  id: string;
  type: string;
  name: string;
  textTemplate: string;
  voice: string;
  speed: number;
  active: boolean;
  createdAt: string;
  updatedAt: string;
}

/** Payload to create or update a locutor template (camelCase in, snake_case on the wire) */
export interface LocutorTemplateInput {
  type: string;
  name: string;
  textTemplate: string;
  voice: string;
  speed: number;
  active: boolean;
}

/** Audio generated by the TTS locutor */
export interface LocutorAudio {
  id: string;
  filename: string;
  filepath: string;
  textRendered: string;
  durationMs: number | null;
  fileSizeBytes: number | null;
  voice: string;
  azuracastMediaId: string | null;
  generatedAt: string;
  status: string;
  hourValue: number | null;
  timeSlotGroup: string | null;
  useCount: number;
  template: { name: string; type: string } | null;
}

/** Entry of the TTS generation log */
export interface LocutorGenerationLog {
  id: string;
  jobType: string;
  status: string;
  details: string | null;
  audiosGenerated: number | null;
  durationMs: number | null;
  startedAt: string;
  finishedAt: string | null;
}

/** Health summary of the TTS locutor */
export interface LocutorStatus {
  kokoro: { healthy: boolean };
  last_job: LocutorGenerationLog | null;
  bank: { ready: number; pending: number; error: number };
  stats: Record<string, unknown>;
  timestamp: string;
}

/** Device registered by the mobile app for FCM notifications */
export interface AdminDevice {
  deviceId: string;
  hasFcmToken: boolean;
  platform: string | null;
  appVersion: string | null;
  subscriptions: string[];
  /** Administrative zone assigned to the device (e.g. a city or region) */
  zoneId: string | null;
  zoneSource?: string | null;
  zoneAssignedAt?: string | null;
  zoneRegion?: string | null;
  zoneCountry?: string | null;
  lastSeen: string;
  createdAt: string;
}

export interface AdminDeviceList {
  rows: AdminDevice[];
  total: number;
  page: number;
  totalPages: number;
}

/** Audience kinds supported by custom push notifications */
export type PushAudience =
  | 'all'
  | 'devices'
  | 'zone'
  | 'platform'
  | 'program'
  | 'active';

/** Payload sent to the backend to preview or send a custom push notification */
export interface PushCampaignInput {
  title: string;
  body: string;
  audience: PushAudience;
  deviceIds?: string[];
  zoneId?: string;
  platform?: string;
  program?: string;
  activeDays?: number;
}

/** Result of sending a push campaign */
export interface PushCampaignResult {
  targeted: number;
  sent: number;
  failed: number;
  invalidTokens: number;
}

/** Entry of the custom push notification history */
export interface PushNotificationLog {
  id: string;
  title: string;
  body: string;
  audience: PushAudience;
  filters: {
    deviceIds?: string[];
    zoneId?: string;
    platform?: string;
    program?: string;
    activeDays?: number;
  } | null;
  targetedCount: number;
  sentCount: number;
  failedCount: number;
  invalidTokens: number;
  createdAt: string;
}

export interface PushNotificationLogList {
  rows: PushNotificationLog[];
  total: number;
  page: number;
  totalPages: number;
}

export interface DeviceZoneList {
  zones: string[];
}

export type ZoneRecalcScope = 'missing' | 'auto' | 'all';

export interface ZoneRecalcStats {
  total: number;
  withZone: number;
  withoutZone: number;
  manual: number;
  auto: number;
  withIp: number;
  withoutIp: number;
  zones: string[];
}

export interface ZoneRecalcInput {
  scope?: ZoneRecalcScope;
  forceManual?: boolean;
  dryRun?: boolean;
  limit?: number;
}

export interface ZoneRecalcResult {
  total: number;
  considered: number;
  updated: number;
  skippedManual: number;
  skippedNoIp: number;
  failed: number;
  dryRun: boolean;
  changes: Array<{
    deviceId: string;
    oldZone: string | null;
    newZone: string | null;
    oldSource: string | null;
    newSource: string | null;
    region: string | null;
    country: string | null;
  }>;
}

/** One media row of a sequential playlist (from AzuraCast playlist order) */
export interface PlaylistOrderEntry {
  /** Row id of the playlist-media association, used to reorder. */
  id: number;
  weight: number;
  media: {
    id: number;
    unique_id: string;
    path: string;
    title: string;
    artist: string;
    length: number;
  };
}

/** Schedule item embedded in the AzuraCast playlist object */
export interface PlaylistScheduleItem {
  id?: number;
  /** Minutes since midnight. */
  start_time: number;
  /** Minutes since midnight. */
  end_time: number;
  /** AzuraCast day indices (1=Monday .. 7=Sunday). */
  days: number[];
}

/** Playlist detail returned by AzuraCast including its schedule */
export interface PlaylistDetail {
  id: number;
  name: string;
  source: string;
  order: string;
  schedule_items?: PlaylistScheduleItem[];
}

/** Rotación automática de playlists (lectura bíblica u otras reglas) */
export interface PlaylistRotation {
  id: string;
  name: string;
  /** Fuente del material: 'playlist' (playlist de AzuraCast) o 'folder' (carpeta de la biblioteca) */
  sourceType: 'playlist' | 'folder';
  sourcePlaylistId: number;
  sourceFolder: string | null;
  targetPlaylistId: number;
  itemsPerDay: number;
  cursor: number;
  loop: boolean;
  active: boolean;
  bibleMode: boolean;
  translation: string | null;
  bibleStartOrdinal: number;
  notifyEnabled: boolean;
  notifyProgram: string | null;
  lastRunAt: string | null;
  createdAt: string;
  updatedAt: string;
  runs?: RotationRunLog[];
}

/** Ejecución registrada de una rotación */
export interface RotationRunLog {
  id: string;
  rotationId: string;
  runDate: string;
  status: 'success' | 'partial' | 'error';
  itemsPicked: number;
  itemsPlaced: number;
  details: string | null;
  createdAt: string;
}

/** Resultado de ejecutar una rotación */
export interface RotationRunResult {
  status: 'success' | 'partial' | 'error';
  itemsPicked: number;
  itemsPlaced: number;
  chapters: { ordinal: number; book: string; chapter: number }[];
  titles: string[];
  errors: string[];
  rotationId?: string;
}

/** Entrada del historial de capítulos emitidos por las rotaciones bíblicas */
export interface BibleReadingHistoryEntry {
  id: string;
  rotationId: string;
  rotationName: string;
  runDate: string;
  /** Fecha (YYYY-MM-DD) del día de emisión en la zona horaria de la estación */
  dateKey: string;
  status: 'success' | 'partial' | 'error';
  itemsPicked: number;
  itemsPlaced: number;
  chapters: { ordinal: number; book: string; chapter: number }[];
}

/** Respuesta pública con la lectura bíblica del día */
export interface BibleReadingToday {
  reading: {
    rotationName: string;
    chapters: { ordinal: number; book: string; chapter: number }[];
  } | null;
}

/** Summary of program push notifications sent (admin dashboard cards) */
export interface NotificationStats {
  totalAll: number;
  total7d: number;
  byProgram: { programId: string; count: number }[];
}

export type NoticeVariant = 'info' | 'event' | 'warning' | 'prayer';
export type NoticeAudience = 'all' | 'zone' | 'platform' | 'program' | 'devices';
export type NoticeDisplayMode = 'toast' | 'modal';

export interface NoticeGalleryItem {
  id: string;
  type: "image" | "video";
  url: string;
  posterUrl: string | null;
  sortOrder: number;
}

export interface AppNotice {
  id: string;
  title: string;
  body: string;
  imageUrl: string | null;
  videoUrl: string | null;
  gallery: NoticeGalleryItem[];
  ctaLabel: string | null;
  ctaUrl: string | null;
  variant: NoticeVariant;
  audience: NoticeAudience;
  audienceZoneId: string | null;
  audiencePlatform: string | null;
  audienceProgram: string | null;
  audienceDeviceIds: string | null;
  displayMode: NoticeDisplayMode;
  startsAt: string;
  endsAt: string;
  maxDisplaysPerUser: number;
  dismissible: boolean;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface AppNoticeList {
  rows: AppNotice[];
  total: number;
  page: number;
  totalPages: number;
}

export type NoticeGalleryItemInput = Omit<NoticeGalleryItem, "id">;

export interface AppNoticeInput {
  title: string;
  body: string;
  imageUrl?: string | null;
  videoUrl?: string | null;
  gallery?: NoticeGalleryItemInput[];
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  variant: NoticeVariant;
  audience: NoticeAudience;
  audienceZoneId?: string | null;
  audiencePlatform?: string | null;
  audienceProgram?: string | null;
  audienceDeviceIds?: string[] | null;
  displayMode: NoticeDisplayMode;
  startsAt: string;
  endsAt: string;
  maxDisplaysPerUser: number;
  dismissible: boolean;
  isActive: boolean;
}

export interface NoticeImage {
  id: string;
  filename: string;
  originalName: string;
  url: string;
  mimeType: string;
  size: number;
  width: number | null;
  height: number | null;
  createdAt: string;
}

export interface NoticeImageList {
  rows: NoticeImage[];
  total: number;
  page: number;
  totalPages: number;
}

export interface NoticeVideo {
  id: string;
  filename: string;
  originalName: string;
  url: string;
  posterUrl: string | null;
  mimeType: string;
  size: number;
  width: number | null;
  height: number | null;
  durationMs: number | null;
  createdAt: string;
}

export interface NoticeVideoList {
  rows: NoticeVideo[];
  total: number;
  page: number;
  totalPages: number;
}

/** Connected worker node reported by the worker pool */
export interface WorkerNodeInfo {
  workerId: string;
  name: string;
  status: string;
  version?: string | null;
  maxConcurrentJobs: number;
  currentJobs: string[] | number;
  currentJobId: string | null;
  lastSeenAt: string | null;
}

/** YouTube processing job with its video summary */
export interface WorkerJob {
  id: string;
  videoId: string;
  status: string;
  attempts: number;
  lastError: string | null;
  startedAt: string | null;
  finishedAt: string | null;
  deadlineAt: string | null;
  nextRetryAt: string | null;
  createdAt: string;
  video: { title: string; videoId: string };
}
