server_tokens off;

limit_req_zone  $binary_remote_addr zone=api:10m      rate=10r/s;
limit_req_zone  $binary_remote_addr zone=general:10m  rate=30r/m;
limit_req_zone  $binary_remote_addr zone=panel:10m    rate=10r/m;
limit_conn_zone $binary_remote_addr zone=conn_limit:10m;

ssl_session_cache   shared:SSL:10m;
ssl_session_timeout 10m;

map $http_origin $cors_origin {
    default                           "";
    "https://lavozverdad.com"         $http_origin;
    "https://www.lavozverdad.com"     $http_origin;
    "https://vozyverdad.com"          $http_origin;
    "https://www.vozyverdad.com"      $http_origin;
}